"""empty message

Revision ID: a315d1bb99f3
Revises: 6007bf751a84
Create Date: 2022-06-05 00:39:49.413463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a315d1bb99f3'
down_revision = '6007bf751a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_at', sa.DateTime(), nullable=True))

    op.execute('UPDATE artists SET created_at = NOW() WHERE created_at IS NULL;')

    op.alter_column('artists', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'created_at')
    # ### end Alembic commands ###
